services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: devops_hackathon_backend
    env_file:
      - ../.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - BACKEND_PORT=${BACKEND_PORT}
      - NODE_ENV=development
    volumes:
      - ../backend/src:/app/src
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - mongo
    expose:
      - "${BACKEND_PORT}"

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile.dev
    container_name: devops_hackathon_gateway
    env_file:
      - ../.env
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT}
      - GATEWAY_PORT=${GATEWAY_PORT}
    volumes:
      - ../gateway/src:/app/src
      - /app/node_modules
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - app_network
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: devops_hackathon_mongo
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    restart: always

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge